### ISSUE TITLE
Request: upgrade testbench 5.1.x for vaadin 8 to selenium 3.11

### ISSUE THREAD

**Issue by gerald24** [vaadin/testbench#1054]
currently testbench 5.1.1 depends on selenium 3.4.0, which is 1 year old.

Please upgrade dependency to selenium 3.11.0

**Comment by johannesh2** [comment]
I'm going to reopen this as it's a valid issue.

**Comment by johannesh2** [comment]
We should test with 3.12.0 and upgrade.

**Comment by gerald24** [comment]
thx
