### ISSUE TITLE
Feature Request: Lambda based ReferenceNameGenerator

### ISSUE THREAD

**Issue by tsuoanttila** [vaadin/testbench#1060]
There's already a concept of `ReferenceNameGenerator` in the `TestBenchCommandExecutor` but there's no simple way to provide a custom reference name generator for my test suite. 

Would be nice to have a way to access for example some static setter with something like `setReferenceNameGenerator((identifier, capabilities ) -> String.format("SomeName_%s_%s", identifier, getCustomString(capabilities)))`.

**Comment by johannesh2** [comment]
PR would be greatly appreciated.

**Comment by tsuoanttila** [comment]
PR provided. Also fixed the #1059 while I was at it. Using this change in the Framework testing, our custom setup around the screenshots dropped to below 90 loc and using this will actually allow us to organise our massive screenshot folder into subfolders.
