### ISSUE TITLE
Update Chrome to 70 breaks APIs in TestBench

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/testbench#1122]
Currently, with testbench `5.2.0`, FW tests (30+ tests) failed after Chrome update to 70.  

like the `clear()` function doesn't work properly. 

i.e.: I have a `combobox` with **pre-selected** value 'A', during tests, i call the `clear()` and send new value 'B'. But what I get is `AB` instead of just 'B'

Possibly some other API is malfunctioning too.

It is blocking FW validation -> https://teamcity.vaadin.com/viewType.html?buildTypeId=Vaadin7Framework_ActiveProjects_FrameworkGitHubValidationBuild20
and FW release https://bender.vaadin.com/viewLog.html?buildId=31855&buildTypeId=VaadinFramework_VaadinFramework86_Testing_TestUITestChrome (we have to roll back the version to 69, in order to make everything work.)

It looks this only affects `comboboxElement`. tried the same with `datefield`, it works fine. 
i have noticed one place, in combobox, the `getInputField()` is finding `By.vaadin("#textbox")` and in datefield, it is `By.tagName("input")`

**Comment by Artur-** [comment]
Are you using the latest ChromeDriver (2.43)?

**Comment by ZheSun88** [comment]
Yes. Actually it is not me, it is the TeamCity.

**Comment by Piuh02** [comment]
This problem persists with testbench 5.2.0, ChromeDriver 2.44 and Chromium 70.0.3538.110.
Any news on this?

**Comment by focbenz** [comment]
I was about to file the same issue as mentioned here when we updated our build server to use the latest Chrome (72) - the tests before with Chrome 54 were passing.
