### ISSUE TITLE
Add additional selectors

### ISSUE THREAD

**Issue by edler-san** [vaadin/testbench#1183]
Writing a testbench test requires a solid understanding of how a given Vaadin application is structured. The DX could be improved by allowing more general selectors.
For example `click("foo")` could click any element having the text "foo" (this could be a radio buttons or regular buttons for instance) as a text/caption.
Another example would be a `near` selector that simply selects the first element of a given type following a specific selection. For instance `click(checkbox(near("search"))`.

Both would allow for a more natural selection of elements.
(Examples were taken from https://taiko.gauge.org/#smart-selectors)

**Comment by GrandyB** [comment]
Not entirely sure about a 'click anything with this caption' kind of use case, but I can certainly say that ElementQuery#caption(String text) that the older versions of testbench that had, was certainly useful.

Currently, there isn't a way to get a ButtonElement by its caption for instance, which seems a bit wild given how common a use case this is. Either have to have a unique ID or class on every button in the system, or write some custom code that does a .all() and compares .getText() on each one, which seems a hacky/slow workaround. The element on the page itself has a 'innerText' property which could surely be  wired into the attribute selector?

Another ElementQuery addition I'd like is .findOnly() (findSingle? findUnique?), which would be the same as doing `Iterables.getOnlyElement($(Element.class).all())` - throwing an exception if there was more than one.
