### ISSUE TITLE
Despite license param / key file trying to verify testbench license via browser

### ISSUE THREAD

**Issue by tlutzavgl** [vaadin/testbench#1272]
Hello vaadin team,

we are currently facing an issue running testbench tests in headless mode as neither using a JVM/Maven param (and maven failsafe systemPropertyVariables) nor using a key file in the hidden .vaadin home dir seem to have any effect: Every time (both on a jenkins build server and locally) testbench is trying to open a browser for validating the license. 

I have been asked by your support to create this issue here and add all specs to reproduce it. These are as follows: 

**Basic specs**

* Vaadin 14.3.1
* Spring Boot 2.2.0-RELEASE
* io.github.bonigarcia.webdrivermanager for managing *only* webdriver for Chrome (the only one used atm.) 
* Maven failsafe plugin for running the testbench ITs within a maven profile "it"

The following excerpt shows the usage of maven failsafe within the "it" profile: 

```
 <profile>
      <id>it</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>start-spring-boot</id>
                <phase>pre-integration-test</phase>
                <goals>
                  <goal>start</goal>
                </goals>
              </execution>
              <execution>
                <id>stop-spring-boot</id>
                <phase>post-integration-test</phase>
                <goals>
                  <goal>stop</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <!-- Runs the integration tests (*IT) after the server is started -->
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-failsafe-plugin</artifactId>
            <version>${maven-failsafe-plugin.version}</version>
              <executions>
                  <execution>
                      <goals>
                          <goal>integration-test</goal>
                          <goal>verify</goal>
                      </goals>
                  </execution>
              </executions>
              <configuration>
                  <trimStackTrace>false</trimStackTrace>
                  <enableAssertions>true</enableAssertions>
                  <systemPropertyVariables>
                     <webdriver.chrome.driver>/usr/bin/chromedriver</webdriver.chrome.driver> <!-- testwise -->
                     <vaadin.testbench.developer.license>-key-</vaadin.testbench.developer.license> <!-- testwise -->
                  </systemPropertyVariables>
                 <argLine>-Dvaadin.testbench.developer.license=-key-</argLine> <!-- testwise -->
                  <includes>
                      <include>**/*IT.java</include>
                  </includes>
              </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
```

The webdriver is configured in a common abstract base class extending 'ParallelTest' using a method annotated with JUnits "@Before" as follows: 

``` 
     ChromeOptions chromeOptions = new ChromeOptions();
      //chromeOptions.setHeadless(true); //used testwise without any difference
      chromeOptions.addArguments("--headless");
      setDriver(TestBench.createDriver(new ChromeDriver(chromeOptions)));
```
Note: Using TestBenchTest instead of ParallelTest does also not make any difference

The tests itself are run via `mvn test verify -Pit -Dvaadin.testbench.developer.license=<key>` 

I noticed the following warnig during the test run which tells me that the systemPropertyVariables and argLine respectively are used but seem to have no effect:
```
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ dsp-web-portal ---
[WARNING] The system property vaadin.testbench.developer.license is configured twice! The property appears in <argLine/> and any of <systemPropertyVariables/>, <systemProperties/> or user property.
```
Above that i also noticed that for validating the license locally my default browser is used while the tests are run via the configured webdriver, which makes me believe that the configuration of the driver may be too late in the application lifecycle ?

Please do not hesitate to ask in case you need any further information. 
Thank you in advance! 

Kind regards,
Timo

**Comment by alvarezguille** [comment]
Hi @tlutzavgl,

`vaadin.testbench.developer.license` is the name of the individual product license used in TestBench for Vaadin 7 and 8.

Starting from vaadin 10+ there is a check for the subscription, not an individual per product license. The name of the property is `vaadin.proKey` you can get the correct value for it and instructions on how to set is a property or a file in [the validation page](https://vaadin.com/pro/validate-license/), the info was corrected recently in this page.

Feel free to re-open or mention me if this doesn't solve your issue.
