### ISSUE TITLE
TestBench dependencies in BOMs shouldn't be of scope test

### ISSUE THREAD

**Issue by simasch** [vaadin/testbench#1321]
All TestBench dependencies like vaadin-accordion-testbench have the scope test in dependencyManagement section of the BOMs.

Now I want to create a test library with common code for all my projects. But due to this scope I have to overridde the scope for all dependencies to compile.

For example:
```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-accordion-testbench</artifactId>
    <scope>compile</scope>
</dependency>
```

IMHO dependencies in dependencyManagement should have the default scope.

**Comment by khmarbaise** [comment]
You describe the same circumstances which I have at the moment... So yes the dependencies in `dependencyManagement` should not have any scope at all...

**Comment by ZheSun88** [comment]
This issue is actually from platform, as we generated the bom from a template which contains the dependencies with scope definition.. 
I will take a look and fix it. Thanks
