### ISSUE TITLE
Setup kotlin compilation for Core module

### ISSUE THREAD

**Issue by caalador** [vaadin/testbench#1328]
To support bringing in the kotlin JUnit features into the project kotlin compilation using the `kotlin-maven-plugin` should be setup for the `vaadin-testbench-core` module

**Comment by mcollovati** [comment]
To have javadocs generated also for Kotlin sources we need to replace maven-javadoc-plugin with [dokka-maven-plugin](https://kotlin.github.io/dokka/1.6.21/user_guide/maven/usage/).
In `vaadin-testbench-core` module we need to replace the plugin in the `release` profile, but also need an additional profile to run `dokka:javadoc` during validation job. The new profile will be activated by the presence of system property `testbench.javadocs`.
