### ISSUE TITLE
Implement a helper class for spring security login

### ISSUE THREAD

**Issue by caalador** [vaadin/testbench#1339]
There should be a helper class that can be used to set the user into the spring security context.
It would be preferable to be able to login before initializing the UI so that a redirect to LoginView
would not happen at all.

Acceptance criteria:
- A helper class is made that can login/logout a user
- Documentation on the feature

**Comment by mcollovati** [comment]
For simple uses cases where only a a specific user is needed, Spring security provides `@WithMockUser` and similar annotations to simulate a logged user.
By default security context is populated before any `@Before(Each)` callback, so when we setup mock Vaadin environment and navigate to the initial page the user details should be already available.

https://docs.spring.io/spring-security/reference/servlet/test/method.html#test-method-withmockuser

This may not be enough for more complex scenarios, for example if developers needs to simulate login and logout with different users in the same test.

However it may be worth to document what can be done with existing Spring helpers, and provide some usage example.

**Comment by knoobie** [comment]
I would suggest to also test that `@WithUserDetails` works properly, because this case is often used in enterprise applications where custom user classes are used. https://docs.spring.io/spring-security/reference/servlet/test/method.html#test-method-withuserdetails

**Comment by mcollovati** [comment]
Spring Security test annotations seems to work fine.
For plain Java projects or Spring projects without Spring Security we can maybe introduce a JUnit Extension/Rule that acts like `@WithMockUser`.
