### ISSUE TITLE
Consider separate artifacts for JUnit 4 and JUnit 5

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/testbench#1363]
Now that [Java UI test project](https://github.com/vaadin/testbench/projects/1) is in progress TestBench has dependencies to both JUnit 4 and JUnit 5
https://github.com/vaadin/testbench/blob/ebb023e1f248529ca23f06c3965b41f5e0025d90/vaadin-testbench-core/pom.xml#L325-L348

This can be inconvenient for users when writing tests as it's possible to accidentally mix JUnit versions and get unexpected results, for instance: wrong imports, wrong annotations or wrong asserts.

One option discussed previously was about having different specific artifacts for JUnit 4 and JUnit 5. There was a previous preparation for this approach from @Artur- by creating a shared module in https://github.com/vaadin/testbench/pull/1318.

**Comment by MarcinVaadin** [comment]
Will be done as part of https://github.com/vaadin/flow/issues/14784

**Comment by MarcinVaadin** [comment]
Changes pushed to https://github.com/vaadin/testbench/pull/1550

**Comment by MarcinVaadin** [comment]
Reopenning as `vaadin-testbench-unit-tests` modules is using both junit4 and junit5 tests and it should also be splitted.
