### ISSUE TITLE
Extend package scanning so definition can be made by class

### ISSUE THREAD

**Issue by caalador** [vaadin/testbench#1420]
Defining package to scan for routes should be extended so that the package(s) to scan could be given as a class(es) (for instance the view class) instead of a string.

Also enabling multiple packages might make sense so you could pinpoint locations to scan.

Lets remove the scanPackages method and add a ViewPackages annotation that has Class[] values and String[] packages.

If the annotation is not present then use "" for scanning else use the defined class packages and string packages for scanning for routes.

Should we have also a boolean for do not scan?

**Comment by mcollovati** [comment]
Does it make sense to have a convention that if the annotation is present but classes and packages are empty, we will scan for annotated class package?

For example the following one will scan for view in `com.vaadin.flow.component.accordion` package, without the need for further declarations

```
package com.vaadin.flow.component.accordion;

@ViewPackages
class AccordionWrapTest extends UIUnitTest {
}
```

**Comment by caalador** [comment]
Sounds like a good idea.
We can always change it if it turns out to be confusing or otherwise bad.

**Comment by cromoteca** [comment]
If I understood correctly what you're trying to achieve, you should add the annotation to `package-info.java` instead.

**Comment by mcollovati** [comment]
The annotation is meant to be per test class.
We can have in the same package several test classes that work different views from the same package.
