### ISSUE TITLE
MockRouteNotFoundError may break tests with restricted view scan and no custom handler

### ISSUE THREAD

**Issue by mcollovati** [vaadin/testbench#1447]
When restricting view scan with `@ViewPackages`, the default `RouteNotFoundError` handler may not be loaded and  
`MockRouteNotFoundError` will be used in place.
The latter always throws a `NotFoundException` when handling the error, so the test may fail during navigation phase.

As a workaround `RouteNotFoundError` can be added to `@ViewPackages`.

Or the test may assert on thrown exception instead of getting the error handling component.
`Assertions.assertThrows(NotFoundException.class, () -> navigate("admin-role", RouteNotFoundError.class));`

Perhaps we can find an easy way to add the default error handler, or at least document the case.

**Comment by caalador** [comment]
RouteNotFoundError should always be registered by the ApplicationRegistry on [setErrorNavigationTargets ](https://github.com/vaadin/flow/blob/fd04f545ee3f13b0cf3cdf2b694c6d9ab215c689/flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java#L146) see 
[initErrorTargets](https://github.com/vaadin/flow/blob/fd04f545ee3f13b0cf3cdf2b694c6d9ab215c689/flow-server/src/main/java/com/vaadin/flow/server/startup/ApplicationRouteRegistry.java#L225)

**Comment by mcollovati** [comment]
So, `MockRouteNotFoundError` is always registered and takes precedence over `RouteNotFoundError`.
Perhaps we can add a `useDefaultRouteNotFoundError` flag on `@ViewPackages` to opt-out the registration of `MockRouteNotFoundError`

**Comment by caalador** [comment]
I didn't note that it throws an exception.
Perhaps the mockRoute should just be changed to just not throw at the end as it doesn't give anything extra by throwing.

**Comment by mcollovati** [comment]
Seems reasonable. I'll remove the throw instruction
