### ISSUE TITLE
Unit test: Calling sendKeys a second time on a WebElement has no effect. How can special characters be sent?

### ISSUE THREAD

**Issue by melDavila** [vaadin/testbench#1449]
### Description of the bug

Calling 2nd time the sendKeys in a WebElement has not efect.

    WebElement webField = $(TextFieldElement.class).waitForFirst();
    webField.sendKeys("Vaadiner");
    webField.sendKeys("TEST");

The field do **not change** the value. must be "TEST" but continue with "Vaadiner"

This works perfectly in v14.

### Expected behavior

This problem in new in v23 and works perfect in v14 and can be avoid in v14  using TextFieldElement and setValue(). 
But affect too to to combo box with datasource. (lazy y load)
Because it is necessary to test the filter tail of the combo box
1. set the filter of combo box 
2. move down
3. press enter
This means 3 times **sendKeys**
tab.sendKeys("MAD");
tab.sendKeys(Keys.ARROW_DOWN,Keys.ARROW_DOWN);
tab.sendKeys(Keys.ENTER);

### Minimal reproducible example

To reproduce the problem:

Download the project:
https://github.com/vaadin/skeleton-starter-flow-spring/archive/v23.zip
Today has vaadin version 23.0.9

And add this methods to the MainViewIT test class to reproduce the problem.

    @Test
    public void setValue_With_WebElement() {
        final WebElement webField = $(TextFieldElement.class).waitForFirst();
        /// USING SENDKEYS 
        webField.sendKeys("Vaadiner");
        webField.sendKeys("DXC TEST");
        $(ButtonElement.class).waitForFirst().click();
        $(NotificationElement.class).waitForFirst();
        Assert.assertTrue($(NotificationElement.class).exists());
        final NotificationElement notification = $(NotificationElement.class).first();
        final String value = notification.getText();
        Assert.assertEquals("Hello DXC TEST", value);
    }

### Versions

- Vaadin / Flow version:  v23
- Java version: 11
- OS version:  Windows 10

**Comment by mcollovati** [comment]
I've tested the above example for the TextField with various Vaadin 14 versions, but it never worked for me.
I can see the two values sent with `sendKeys` concatenated in the input field, and the notification never shows it.

For the Combobox use case, as @TatuLund  suggested in the referenced issue, using the ComboBoxElement is the way to go.
Components may change their structure over time and TestBench API will reflect this changes, so that tests written with previous versions will continue to work, but I think compatibility cannot be guaranteed if the test uses selenium API directly.

**Comment by TatuLund** [comment]
> I've tested the above example for the TextField with various Vaadin 14 versions, but it never worked for me.

Yes, I assume that is becaumse of missing `field.setAutoselect(true);`

**Comment by mcollovati** [comment]
And, as expected, if you do not trigger blur, even with autoselect the text gets concatenated becuase the field already has focus

**Comment by mshabarov** [comment]
Issue is being closed because no more feedback provided for a long time. If you still have a questions, please reopen it or create a new one.
