### ISSUE TITLE
Grid column texts are reported in an unexpected order

### ISSUE THREAD

**Issue by Artur-** [vaadin/testbench#1473]
When using `grid.getCellText(row, column)` I would expect the column index to refer to the index on screen and not some internal index in grid. Hidden columns should be discarded and if the columns have been reordered, then that is the order that should be used for `getCellText`

**Comment by mcollovati** [comment]
`getCellText` seems to work correctly with columns reorder. 
Created a test in #1483

**Comment by caalador** [comment]
Closing issue as with 1472 it should work as described and expected in ticket
