### ISSUE TITLE
ElementQuery - attributeContains rework

### ISSUE THREAD

**Issue by GrandyB** [vaadin/testbench#1554]
I've been caught out a couple of times by ElementQuery#attributeContains by the fact that it's not like the String 'contains' method.
"attributeContains" makes me think that whatever I provide exists anywhere within the actual attribute value as a substring (aka, `*=` matcher rather than the current `~=` matcher).

I would suggest this method be split.
`~=` could be a "attributeContainsEntry" or "attributeHasPart" method, while
`*=` would be used in "attributeContains".

It's rough that there's no way to implement our own extensions or forks of ElementQuery in order to add this functionality ourselves, but perhaps that's a submission for another time.

**Comment by joelpop** [comment]
Note, `attributeContains` is being deprecated in lieu of `withAttributeContaining`, so now would be a good time to fix this. I suggest:
`~=` → `withAttributeContainingToken`
`*=` → `withAttributeContaining`
