### ISSUE TITLE
withCaption should be renamed withLabel

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/testbench#1593]
To query a label, you can do this:
```
$(CheckBox.class).withPropertyValue(Checkbox::getLabel, "Remember me").first()
```
or:
```
Checkbox rememberMeCheckbox = $(Checkbox.class).withCaption("Remember me").first();
```

But caption is the name used in Vaadin 8 and label is used in Flow.

Internally withCaption will query the label if it's not a Button and the text if it's a button.
It's using this: https://github.com/vaadin/testbench/blob/master/vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/ComponentUtils.kt#L358

My suggestion is to deprecate withCaption and create a new method withLabel that uses internally 
https://github.com/vaadin/testbench/blob/master/vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/ComponentUtils.kt#L332

**Comment by joelpop** [comment]
Maybe not. These methods do not just select on field captions, they also select on button text.

I see "caption" as a generic way to refer to a component's visual name. For fields, this visual name is shown via a label or a placeholder, and for buttons, this name is shown as its text.

I suggest keeping the `withCaption[Containing]` selector methods, but expand them to be more like the new, identically-named selector methods in `ElementQuery`. This is how `ElementQuery` does it: For fields, these methods use the label if it exists, but if the label does not exist, it uses the placeholder instead. This makes sense from a UI perspective. For buttons, these methods use the text. The `withCaption[Containing]` selector methods of `ComponentQuery` have the same implementation with the exception of checking the placeholder in the absence of a label.

In addition, I suggest adding new selector methods for `withLabel[Containing]` and `withPlaceholder[Containing]`. There is no need to add selector methods for `withText[Containing]` as they already exist.

This approach is much less of a breaking change and retains the "smart" caption selector methods.

**Comment by joelpop** [comment]
See #1784 (feat: add conditional (non-attribute) selectors to ElementQueries) and #1786 (feat: rework "containing" selectors via addition of remaining attribute operators).

**Comment by joelpop** [comment]
This issue is obsolete.

`withCaption` has been retained as a generic way to obtain a label/placeholder (for fields) or text (for buttons). To explicitly target labels, placeholders, and button captions, use `withLabel`, `withPlaceholder`, and `withText`, respectively.
