### ISSUE TITLE
Add Testers for SideNav, TabSheet and MultiSelectComboBox / UI Unit Tests

### ISSUE THREAD

**Issue by TatuLund** [vaadin/testbench#1635]
New components, notably SideNav, TabSheet and MultiSelectComboBox seem to lack Testers.

**Comment by czp13** [comment]
Thanks, Tatu. Shall be put here probably:
- https://github.com/vaadin/testbench/tree/main/vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component

**Comment by TatuLund** [comment]
@czp13 exactly.
