### ISSUE TITLE
BrowserExtension, It should be possible to pass browser parameters

### ISSUE THREAD

**Issue by manolo** [vaadin/testbench#1681]
When running tests in certain systems like agents in TC, it's necessary to pass the `--no-sandbox` parameter to chrome, because tests are run as root in a docker container.

Right now there is no way to add extra capabilities to the driver when using the `BrowserExtension` class, the only way is to provide the driver by implementing DriverSupplier and deal with all the code necessary to create the driver depending on whether it's local, remote, etc. Basically repeat the same [code](https://github.com/vaadin/testbench/blob/main/vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/browser/BrowserExtension.java#L204) that is already in `BrowserExtension` but adding the extra parameter.

For example this [hack](https://github.com/vaadin/snaplets-internal/pull/22/files#diff-9d3ffbd71cc2c303333255f314568b6116f6d39cd1385df2de84b80a40916080R26) was needed in the Snaplets project.

**Comment by Artur-** [comment]
> tests are run as root in a docker container

Just pointing out the obvious that this is not considered best practice

**Comment by manolo** [comment]
Yep but it's what we have in TC, but anyways there could be other parameters that developer would want to pass
