### ISSUE TITLE
totalTimeSpentRendering and totalTimeSpentServicingRequests fail

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/testbench#1704]
Neither `totalTimeSpentRendering` nor `totalTimeSpentServicingRequests` considers `Flow.clients.TypeScript` (see https://github.com/vaadin/flow/issues/7514).

In consequence, `totalTimeSpentRendering` fails with: 
```
org.openqa.selenium.JavascriptException: javascript error: Performance data is not available in production mode 
```

and `totalTimeSpentServicingRequests` fails with:
```
window.Vaadin.Flow.clients[client].poll is not a function
```

Vaadin 24.2.5

**Comment by mshabarov** [comment]
Apparently `getProfilingData()` and `poll()` functions aren't implemented for `TypeScript` client.
Until these two are implemented in (Hilla ?), we might need to check if `poll()` function is defined before calling it, and check if the client is of type "TypeScript" before checking it. This at least would fix the API for Hilla applications.
