### ISSUE TITLE
Wait for dev bundle build in waitForVaadin

### ISSUE THREAD

**Issue by mshabarov** [vaadin/testbench#1705]
Vaadin Flow 24.3 has now a "Building front-end development bundle" spinner shown on the page when dev bundle is being generated, see [this issue](https://github.com/vaadin/flow/issues/16607).

TestBench should take this into account in `waitForVaadin` [method](https://github.com/vaadin/testbench/blob/06271bd9ca67c61e4a04a3dc07ee32bc771074c9/vaadin-testbench-shared/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java#L107) to let Flow apps to properly wait until custom dev bundle is ready.

Possible solution is to wait until spinner div 
```xml
<div class="message">Building front-end development bundle</div>
```

disappears, like shown below:

```java
waitUntil(driver -> {
            try {
                TestBenchElement testBenchElement = $("div").attribute("class", "message").waitForFirst();
                return testBenchElement == null;
            } catch (TimeoutException e){
                return true;
            } catch (NoSuchElementException e){
                return true;
            }
        });
```

**Comment by TatuLund** [comment]
I have used slightly different wayt to do the same 

https://github.com/TatuLund/bean-table/blob/v24/src/test/java/org/vaadin/tatu/AbstractViewTest.java#L123

**Comment by mshabarov** [comment]
UPD: TestBench `waitForVaadin` method already has a check for dev server [here](https://github.com/vaadin/testbench/blob/06271bd9ca67c61e4a04a3dc07ee32bc771074c9/vaadin-testbench-shared/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java#L60C44-L60C44).

This checks for a flag `devServerIsNotLoaded` which is added on "dev mode not ready" page [here](https://github.com/vaadin/flow/blob/c8edbf0c3a77cf57bc1af65af3df419c2defa149/vaadin-dev-server/src/main/resources/com/vaadin/base/devserver/dev-mode-not-ready.html#L52).

We should start with testing the `waitForVaadin()` method properly waiting until custom dev bundle build in Spring+Flow skeleton starter project with JS customisations.
