### ISSUE TITLE
CheckboxElement#click() fails with TestBench 5.2.0

### ISSUE THREAD

**Issue by TatuLund** [vaadin/testbench#1741]
Vaadin 8, TestBench 5.2.0:

CheckboxElement.click() method with Chrome 121+ is now throwing the following except

org.openqa.selenium.ElementClickInterceptedException - element click intercepted: Element <input type="checkbox" value="on" id="gwt-uid-18" tabindex="0"> is not clickable at point (631, 146). Other element would receive the click: <label for="gwt-uid-18">...</label>

After working with Javier we found that this did work

checkBox.getCommandExecutor().executeScript("arguments[0].click()", checkBox.getInputElement());

**Comment by TatuLund** [comment]
This was easy to replicate, but the root cause of the problem was less obvious. I just by accident noticed that how Chrome reports browser name has changed and it uses different string with headless mode and non-headless.

**Comment by mshabarov** [comment]
@TatuLund can we close this issue as the referenced PR has been merged already?

**Comment by TatuLund** [comment]
@mshabarov sure, I thought it was autoclosed already.
