### ISSUE TITLE
TextFieldElement problem with setValue

### ISSUE THREAD

**Issue by mgeuer** [vaadin/testbench#1747]
The TextFieldElement should not take the first input field since it is allowed to add a component for the helper slot in a TextField. It should check for the correct slot or take the last one.

The following code can reproduce the problem:
```
TextField textField = new TextField();
textField.setId("test");
textField.setHelperComponent(new Checkbox("Delete"));
```

This TextField can't be set using $(TextFieldElement.class).id("test").setValue("example")

**Comment by TatuLund** [comment]
According to documentation interactive components are sort of discouraged in Helper.

![image](https://github.com/vaadin/testbench/assets/14309836/a1c19a3a-6732-47e0-9b94-fd213887432f)

It would be interesting to know what is your actual use case here, why you have another input in the Helper?

**Comment by TatuLund** [comment]
Helper is not the right way to do that. You should instead wrap Checkbox and TextField in the same layout component.

**Comment by mgeuer** [comment]
Ok, thank you for the explanation
