### ISSUE TITLE
Dragging and Dropping + screenshot using WebDriver will not produce pictures expected

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#487]
**Originally by _Johan Anas_**

___
new Actions(driver).moveToElement(findWebElementBy(locator), offset.x, offset.y ).clickAndHold().perform();

followed by

new Actions(driver).moveToElement(e, offset.x, offset.y).perform();

and a screenshot, didn't show any dragged element when i tested locally with Chrome22 and FireFox10. But using Arturs hub (http://172.16.10.16:4444/wd/hub) + Firefox10-driver, the element appeared at the right side of the picture. At the same time the picture was stretched beyond normal boundaries. Probably as much as the width of the dragged element.
(see HeaderClick.html)

A few screenshots added

___
 Imported from https://dev.vaadin.com/ issue #10054

**Comment by Artur-** [comment]
This is a very old issue for old browser versions. Please reopen if it is still relevant
