### ISSUE TITLE
Screen shot of only a certain area of the screen

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#506]
**Originally by @zch**

___
The WebDriver API supports screen shots of certain elements (and their children), but I don't know which browsers actually implement the API.

Another way to implement the same thing is to use masked screen shots and mask out everything but the interesting area.

This is mostly a documentation thing, i.e. which browsers support the API and how to use masking to achieve the same thing.

___
 Imported from https://dev.vaadin.com/ issue #10349

**Comment by Artur-** [comment]
This was implemented in f8209900ff6f138b171e7b87e4b100603f25dce9
