### ISSUE TITLE
Support running tests on Chromium based Opera

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#571]
**Originally by @Artur-**

___
It should be possible to run tests on Opera 15+ which are based on Chromium. The current OperaDriver only supports Opera up to 12 and ChromeDriver does not support Opera 15+ either.

___
 Imported from https://dev.vaadin.com/ issue #12800

**Comment by Artur-** [comment]
This is a Selenium/OperaDriver feature, not a TestBench feature
