### ISSUE TITLE
TestBench accessing ComboBox Popup.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#638]
**Originally by _Dmitrii Rogozin_**

___
ComboBoxElement class in TestBench add-on doesn't provide method for accessing a popup. There is a openPopup method but it returns void.
So right now, TestBench doesn't allow to test navigating in comboBox popup via arrows or typing.

The use case for this feature is to test navigating to the particular item in a popup and geting it's value. May be performed via Selenium like that:

```
 WebElement dropDownComboBox = driver.findElement(By
                .className("v-filterselect-input"));
        // navigate in popup
        dropDownComboBox.sendKeys(Keys.DOWN);
        dropDownComboBox.sendKeys(Keys.DOWN);
        //get selected items
        List<WebElement> items = driver.findElements(By
                .className("gwt-MenuItem-selected"));
```

___
 Imported from https://dev.vaadin.com/ issue #13756

**Comment by Artur-** [comment]
`ComboBoxElement.getSuggestionPopup` was added in 954477108169f9d7b810a1a6433694cc578c5ac4
