### ISSUE TITLE
API for the different DateFieldElements

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#643]
**Originally by @Artur-**

___
Common API:

PopupDateField:
 - openPopup() - should return an Element with the same API as InlineDateFieldElement (below)
 - sendKeys(), clear() should target the input element
 - setVaue(String) should work as for TextField

InlineDateField + "DatePopupElement"
 - nextMonth()
 - prevMonth()
 - nextYear()
 - prevYear()
 - clickDate(int)
 - selectHour(int)
 - selectMinute(int)
 - selectSecond(int)
 - selectAM()
 - selectPM()

**Comment by Artur-** [comment]
This issue was moved to vaadin/framework#8191
