### ISSUE TITLE
TestBench Element classes should be annotable with Class<?> in addition to String

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#656]
**Originally by @tsuoanttila**

___
@ServerClass annotation takes a String argument that is basically (Class<?> clazz).getCanonicalName(). When one can be sure that the actual class and element class are in the same class path it would be very helpful to use MyWantedClass.class instead of writing the full class name. This should make refactoring easier, and ease the creation of new Element classes.

I'd suggest renaming the current annotation to @ServerClassName and implement @ServerClass for Class<?>.  Annotation handling is done only in one function of ElementQuery so the change is not too big.

___
 Imported from https://dev.vaadin.com/ issue #13979

**Comment by Artur-** [comment]
This is by design
