### ISSUE TITLE
Notification problems with Testbench 4 and Calendar

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#669]
**Originally by @Ansku**

___
Attempts to convert NotificationTestUI's (already failing) TB2 test CalendarNotifications to TB4 were met with multiple notification problems:

- Notification.show gets called for everything but IEs never show a notification in screenshots. For IE8 that can be remedied by removing calendar.markAsDirty() from the click that creates an event and triggers the notification, but then the event won't become visible.

- None of the other browsers seem to care about the moveByOffset when it comes to closing notifications, although PhantomJS notification fades by itself.

- Only Firefox notification can be closed with $(NotificationElement.class).first().closeNotification(); -- Chrome gets StaleElementReferenceException even if there is still a visible notification in the screenshots.

Test class attached with corresponding FIXMEs included.

___
 Imported from https://dev.vaadin.com/ issue #14312

**Comment by Artur-** [comment]
This issue was moved to vaadin/framework#8195
