### ISSUE TITLE
Remove "You are using an unsupported command-line flag" warning when running tests locally on Chrome.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#673]
**Originally by _Dmitrii Rogozin_**

___
When running tests locally with Chrome, a "You are using an unsupported command-line flag: --ignore-certifcate-errors." warning appears. Happens with Chromve v 35.
The problem is reported here: 
​https://code.google.com/p/chromedriver/issues/detail?id=799

Already fixed in vaadin project #14319, should be fixed in TB4

___
 Imported from https://dev.vaadin.com/ issue #14332

**Comment by Artur-** [comment]
According to https://bugs.chromium.org/p/chromedriver/issues/detail?id=799, this was fixed in ChromeDriver 2.11
