### ISSUE TITLE
TableElement should have a better way to check that a cell/row/column doesn't exist, and a way for getting row/column count

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#685]
**Originally by @Ansku**

___
It would be nice to have some easier way to check that there are no rows after the expected final row than checking that tableElement.getCell(<rowcount>,0) throws NoSuchElementException or having an assert such as:
```
assertTrue(tableElement.findElements(By.vaadin("#row[<rowcount>]/col[0]")).isEmpty());
```

To that effect (and for many other uses) it would also be nice to be able to query the current row count -- especially for TreeTableElement where expanding and collapsing rows keeps changing the count, but also for TableElement itself.

___
 Imported from https://dev.vaadin.com/ issue #14417

**Comment by Artur-** [comment]
This and other enhancements are available for `Grid` in `GridElement`.
