### ISSUE TITLE
Implement getValue method for TableElement and TreeTableElement

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#699]
**Originally by @zch**

___
Implement getValue method for TableElement and TreeTableElement.

Currently it is not clear what this method should return, one suggestion was to return a string of format: row index/concatenating string of all columns values of first selected row. 
The problem with this approach, that because of lazy loading not all rows are represented on the client side, so you can't count the index.

**Comment by Artur-** [comment]
Sounds like there is not a clear use case for this so let's not do it.
