### ISSUE TITLE
Unify SubPartAware APIs

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#702]
**Originally by @tsuoanttila**

___
SubPartAwareness is done differently in all the components. There should be somehow unified way of using subparts on client side and in test bench element APIs.

___
 Imported from https://dev.vaadin.com/ issue #14530

**Comment by Artur-** [comment]
This is very vague and mostly related to the framework components and their SubPart implementation, so closing this TestBench issue
