### ISSUE TITLE
IE9, IE10 and IE11 occasionally fail to click with TestBench

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#705]
**Originally by _mgrankvi_**

___
At times IE versions 9-11 seem to occasionally fail click() calls. Sometimes this can be "fixed" with 2 click() calls after each other, but even this fails at times.

This might well be due to the problem noted here: http://jimevansmusic.blogspot.fi/2012/06/whats-wrong-with-internet-explorer.html

___
 Imported from https://dev.vaadin.com/ issue #14567

**Comment by Artur-** [comment]
This is indeed a problem in InternetExplorerDriver and not in TestBench
