### ISSUE TITLE
TextFieldElement.setValue sends enter - it should not

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#722]
**Originally by @Artur-**

___
TextFieldElement.setValue should set the value and ensure an onchange event occurs in the browser. It cannot send an enter key event because this can have side effects, such as causing a login in a login form (like on http://dashboard.demo.vaadin.com).

___
 Imported from https://dev.vaadin.com/ issue #14875

**Comment by Artur-** [comment]
This was fixed in eb41933
