### ISSUE TITLE
ElementQuery.caption(String) should return the first element, not all elements

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#726]
**Originally by @Artur-**

___
When you want to find the one and only element with a given caption you use
```
$(TextFieldElement.class).caption("First Name")
```
which returns `ElementQuery` so you have to still add `.first();` to get the actual element.

This is counter intuitive as the caption typically uniquely identifies the element and you want the first one (similarly to `id(...)` which returns the element directly). 

___
 Imported from https://dev.vaadin.com/ issue #14907

**Comment by Artur-** [comment]
Technically would be incorrect and has not been a huge problem, so let's not do it
