### ISSUE TITLE
Implement getCaption method for classes extending AbstractSingleComponentContainerElement

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#748]
**Originally by _mathieu.ouellet.1@dti.ulaval.ca_**

___
Ticket #14453 was supposed to implement getCaption method to all testbench element classes, but is missing for PanelElement, WindowElement and UIElement and calling getCaption on them throws a NoSuchElementException on aria-labelledby (i.e. AbstractComponentElement implementation)

___
 Imported from https://dev.vaadin.com/ issue #15190

**Comment by Artur-** [comment]
`WindowElement.getCaption()` exists in vaadin-testbench-api 7.7.6 at least. `UIElement.getCaption` is not needed as a `UI` cannot have a caption.

**Comment by Artur-** [comment]
PanelElement covered by https://github.com/vaadin/framework/issues/8189
