### ISSUE TITLE
Additional API for WindowElement

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#749]
**Originally by _mathieu.ouellet.1@dti.ulaval.ca_**

___
Add methods to WindowElement :
- close(), see `v-window-closebox`,
- maximize(), see `v-window-maximizebox`,
- restore(), see `v-window-restorebox`

Also add isClosable() and isMaximized().

___
 Imported from https://dev.vaadin.com/ issue #15191

**Comment by Artur-** [comment]
This API exists at least in vaadin-testbench-api 7.7.6
