### ISSUE TITLE
ComboBoxElement.clear() should clear the selection

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#751]
**Originally by @Ansku**

___
Currently `$(ComboBoxElement.class).first().clear();` gives me
`org.openqa.selenium.WebDriverException: Element must be user-editable in order to clear it.`

___
 Imported from https://dev.vaadin.com/ issue #15215

**Comment by mvysny** [comment]
Probably reappeared in later TestBench: https://github.com/vaadin/flow-components/issues/1685
