### ISSUE TITLE
TestBench query fails when multiple vaadin portlets are on a single page

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#756]
**Originally by _roflkoptr_**

___
I have 2 vaadin portlets on a single page in liferay portal. Each has its own UI and a Button component in it.
When testing the page, I am trying to find both buttons on the page using this query:
```
$(ButtonElement.class).all();
```
I expect the query to return both buttons in a list. But only the button from the first portlet is returned.
On the other hand, querying each of the buttons separately using findElement(By.vaadin(...)) works fine. So I made the following simple test to see what works and what doesn't:
```
@Test
public void findAllButtons() {          //fails
	assertTrue($(ButtonElement.class).all().size() == 2);
}

@Test
public void findFirstButton() {         //passes
	$(ButtonElement.class).id("button_1").click();
}

@Test
public void findSecondButton(){         //fails
	$(ButtonElement.class).id("button_2").click();
}

@Test
public void findElementByVaadin(){       //passes
	findElement(By.vaadin("//com.vaadin.ui.Button[caption='button_2']"));
}

@Test
public void findElementsByVaadin(){     //fails
	findElements(By.vaadin("//com.vaadin.ui.Button[caption='button_2']")).get(0);
}
```

Source of the portlets and test is in attachment.

My speculation (might be totally wrong): 
From the results of the test, it seems that findElement works fine but findElements returns only results from the first portlet on the page. After quickly browsing through the code I think that I found the problem.
In method TestBenchDriverProxy#executeSearch, the script fragment created by:
```_ Construct elementSelectionString script fragment based on type of
_ search context
String elementSelectionString # "var elementclients[client]."
        + jsFunction;
if (context instanceof WebDriver) {
	elementSelectionString += "(arguments[0]);";
} else {
	elementSelectionString += "StartingAt(arguments[0], arguments[1]);";
}

String findByVaadinScript # "var clientswindow.vaadin.clients;"
		+ "for (client in clients) {" + elementSelectionString
		+ "  if (element) {" + " return element;" + "  }" + "}"
		+ "return null;";
```
does not work for jsFunctions getElementsByPath and getElementsByPathStartingAt. They return an empty array when nothing is found, so the "if (element) {" part of the script is always true. getElementByPath and getElementByPathStartingAt return null when nothing is found, so it works for them.

___
 Imported from https://dev.vaadin.com/ issue #15295

**Comment by qwikso** [comment]
Hi Vaadin/TestBench guys,
can you make a review and final statement about this issue? Since Vaadin officially supports Liferay portlets, it's really annoying that applications with multi-portlet pages are not testable at all. And unbelievably, this issue is 4 years old:(

All TestBench versions (4.x, 5.x) are affected.

Regards,
Q.

**Comment by johannesh2** [comment]
We'll take this one under investigation and hopefully fix this in the next sprint.

**Comment by DiegoCardoso** [comment]
Fixed by #1067, #1069 and #1071

**Comment by qwikso** [comment]
@DiegoCardoso great job Diego. When may we expect a release of 4.x (4.2.2 or 4.3) version to apply a fix in our code? We are still sticking to Vaadin 7.

**Comment by DiegoCardoso** [comment]
We are planing to release it soon. Within the few weeks, I'd say.
