### ISSUE TITLE
Sensible getValue() and setValue() for RichTextAreaElement

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#768]
**Originally by @Ansku**

___
There should be a sensible way for getting the text contents of RichTextAreaElement.

___
 Imported from https://dev.vaadin.com/ issue #16578

**Comment by hesara** [comment]
Issue moved to [vaadin/framework #8184](https://github.com/vaadin/framework/issues/8184) via [**ZenHub**](https://www.zenhub.com/)
