### ISSUE TITLE
$(MenuBarElement.class) click item does select correct item if name occurs twice in menu bar

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#776]
**Originally by _kamuffe_**

___
Hi.

Consider the following menubar hierarchy:

    File
        new
            item1
            item2
            item3
    item1'

The two items item1 and item1' are the same string, I use the ' only to distinguish between the two items.
If I now try to select item1 I do this like this:

$(MenuBarElement.class).first().clickItem("File", "new", "item1");

But testbench selects item1'

From my point of view this is not what I would expect. I expect that item1 gets selected.

Thanks,
Christoph

___
 Imported from https://dev.vaadin.com/ issue #16874

**Comment by Artur-** [comment]
Covered by vaadin/framework#8186

**Comment by TatuLund** [comment]
If you set the MenuBar id, say "my-menu", the menu items will have generated id's "my-menu-1", "my-menu-2", ...
