### ISSUE TITLE
TestBench leaves IE temp files behind, filling up the disk

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#783]
**Originally by @Artur-**

___
`c:/users/<user>/appdata/local/temp` contains a lot of files named `IED<4 hex chars>.tmp`, all with either size 0 or the same size (~2500KB). Probably comes from https://github.com/SeleniumHQ/selenium/blob/01399fffecd5a20af6f31aed6cb0043c9c5cde65/cpp/iedriverserver/IEDriverServer.cpp#L214

___
 Imported from https://dev.vaadin.com/ issue #18277

**Comment by Artur-** [comment]
Should be fixed in IEDriver, not TestBench
