### ISSUE TITLE
TableElement.getRow() should return the <tr> element, not the <td> inside it.

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#785]
**Originally by @thinwire**

___
When doing `$(TableElement.class).first().getRow(0).getHTML()`, I noticed I'm getting the `<td>` element from inside the row, not the `<tr>` element itself. This is rather annoying, since the <tr> element contains the v-selected css class annotation I'm after.

Furthermore, after doing `TableElement te = $(TableElement.class).first(); te.getCell(0,0).click();`, the next call to `te.getCell(0,0).isSelected();` still returns false. As does the isSelected() call to the row.

___
 Imported from https://dev.vaadin.com/ issue #18336

**Comment by Artur-** [comment]
Possibly `WebElement.getAttribute("outerHTML")`. Closing this issue as there is no bug
