### ISSUE TITLE
Cannot click on checkbox with Chrome 41 when using Valo

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/testbench#788]
**Originally by @Artur-**

___
```
            $(CheckBoxElement.class).caption("Include details").first().click();
```

fails with the error
```
org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (45, 69). Other element would receive the click: <label for="gwt-uid-2">...</label>
```

Probably related to the fact that Valo positions a pseudo ::after element on top of the checkbox input element

___
 Imported from https://dev.vaadin.com/ issue #18368

**Comment by Artur-** [comment]
Seems to have been fixed in 954477108169f9d7b810a1a6433694cc578c5ac4
