### ISSUE TITLE
Infinite loop with TestBench 4.2.0 and Selenium 3.6.0 when using WebDriverWait

### ISSUE THREAD

**Issue by qwikso** [vaadin/testbench#945]
Hello folks,

I know the Selenium 3.6.0 is not yet oficially supported, but I'm already using it with TestBench 4.2.0 and there is no significant problem excepting the following one: **when WebDriverWait is used and timeout exception happened Selenium will hang up in an infitine loop**.

**There is one very important change in Selenium. It tries to iterate through the chain of wrapped drivers.**
Check the modification here: https://github.com/SeleniumHQ/selenium/commit/2494e69275c3e82b63f8413a506856ac200954ec

**The problem is the TestBenchDriverProxy implements the getWrappedDriver() method in a very strange way and returns itself (return this;).** Bang and infinite loop is here!

Can you fix it please as soon as possible?
Thanx and best regards!

**Comment by alvarezguille** [comment]
Thanks for reporting this, it is probably fixed by #937, we can port it back to TB 4 if it doesn't cause any regressions or new issues

**Comment by qwikso** [comment]
Yes, that's the right fix. Great and I'm looking forward to see it in TestBench 4.x!
